language: node_js

node_js: "12"

services:
  - docker

install:
  - export DOCKER_FULL_IMAGE_NAME=agusnez/contacts-api
  - docker build -t $DOCKER_FULL_IMAGE_NAME:$TRAVIS_COMMIT .
  - docker build -t $DOCKER_FULL_IMAGE_NAME:latest .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push agusnez/contacts-api:$TRAVIS_COMMIT
  - docker push agusnez/contacts-api:latest

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/image_pull
  on:
    branch: master