language: node_js

node_js: "12"

services:
  - docker

install:
  - export DOCKER_FULL_IMAGE_NAME=agusnez/contacts-api:$TRAVIS_COMMIT
  - docker build -t $DOCKER_FULL_IMAGE_NAME .

deploy:
  provider: script
  script: bash scripts/docker_push
  on:
    branch: master