#!/bin/bash
wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit.tar.gz
tar -xvf openshift-origin-server-v3.11.0-0cbc58b-linux-64bit.tar.gz
mv openshift-origin-server-v3.11.0-0cbc58b-linux-64bit oc-tool
cd oc-tool
./oc login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER
./oc project demo
./oc import-image agusnez/contacts-api:latest